name = "SpatialFileIO"
uuid = "ab380219-86f4-46ea-9ab2-f0efd05bc343"
version = "0.8.1"
authors = ["Clare Webster <clare.s.webster@gmail.com> and contributors"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
PointClouds = "3cc211ed-1f43-4d33-a894-629186066e97"

[compat]
PointClouds = "1.1.2"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
